name: Build and Deploy
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Setup .NET Blazor workload
        run: dotnet workload install wasm-tools

      - name: Publish solution
        run: dotnet publish PV260Demo.App/PV260Demo.App.csproj -c Release -o ./publish

      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          path: publish
          name: PV260Demo
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Run tests
        run: dotnet test PV260Demo.Tests/PV260Demo.Tests.csproj

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    permissions: 
      pages: write
      id-token: write
      contents: read
    environment: github-pages
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: PV260Demo
          path: publish

      - name: Upload Artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: publish/wwwroot

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4
          
