# github action to build blazor webassembly app
name: Build and Deploy
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Setup .NET Blazor workload
        run: dotnet workload install wasm-tools

      - name: Publish solution
        run: dotnet publish PV260Demo.App/PV260Demo.App.csproj -c Release -o ./publish

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: publish/wwwroot
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          
        