# github action to build blazor webassembly app
name: Deploy
on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: write
    steps:
      - name: Download artifacts from build
        uses: actions/download-artifact@v4
        with:
          name: PV260Demo
          path: publish

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: publish/wwwroot
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

